all: floodfill sincurlimage

floodfill: FloodfillTool.cpp floodfill.cpp floodfill.h
	g++ -fPIC -shared -o FloodfillTool.so floodfill.cpp FloodfillTool.cpp

sincurlimage: SincurlImgTool.cpp sincurlimage.cpp sincurlimage.h
	g++ -fPIC -shared -o SincurlImgTool.so sincurlimage.cpp SincurlImgTool.cpp
